use PharmacyManagment;
SET IDENTITY_INSERT [dbo].[AspNetRoles] ON
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (1, N'Home Page', N'HOME PAGE', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (2, N'User Roles', N'USER ROLES', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (3, N'Role Assign', N'ROLE ASSIGN', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (4, N'List Customers', N'LIST CUSTOMERS', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (5, N'Customer Details', N'CUSTOMER DETAILS', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (6, N'Create Customer', N'CREATE CUSTOMER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (7, N'Edit Customer', N'EDIT CUSTOMER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (8, N'Delete Customer', N'DELETE CUSTOMER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (9, N'List Manufacturer', N'LIST MANUFACTURER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (10, N'Manufacturer Details', N'MANUFACTURER DETAILS', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (11, N'Create Manufacturer', N'CREATE MANUFACTURER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (12, N'Edit Manufacturer', N'EDIT MANUFACTURER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (13, N'Delete Manufacturer', N'DELETE MANUFACTURER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (14, N'List User', N'LIST USER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (15, N'Register', N'REGISTER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (16, N'User Details', N'USER DETAILS', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (17, N'Edit User', N'EDIT USER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (18, N'Delete User', N'DELETE USER', NULL)
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (19, N'Profile', N'PROFILE', NULL)
SET IDENTITY_INSERT [dbo].[AspNetRoles] OFF
